# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '4a8ac2c3-70d0-40bf-b64c-5298f806af48'
  imageRepository: 'rjammalamadakapipeline'
  containerRegistry: 'acrajscseeds.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureCLI@1
      inputs:
        azureSubscription: AJSC
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name acrajscseeds.azurecr.io --username 73135416-1e48-48a6-9a72-53fb8ffc970e  --password 9be0aec9-84a5-4c71-bbfc-ffb37d9f206b
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
